# Use the latest Ubuntu image as the base, and specify the platform as linux/amd64
FROM --platform=linux/amd64 ubuntu:latest

# Install necessary packages (curl, rsync, git)
RUN apt-get update && \
    apt-get install -y curl rsync git

# Set working directory
WORKDIR /app
VOLUME /urbit

COPY ../desk /app/desk
COPY ../talk /app/talk

ENTRYPOINT ["/urbit/entrypoint_rube.sh"]

