import type { Entry } from './types';

export const notes = {
  published: {
    kind: 'scry',
    agent: 'notes',
    path: '/v0/published',
    since: '12.2.0',
  },
  stream: {
    kind: 'subscribe',
    agent: 'notes',
    path: '/v0/notes/{host}/{name}/stream',
    since: '12.2.0',
  },
  said: {
    kind: 'subscribe',
    agent: 'notes',
    path: '/v0/said/{host}/{name}/note/{id}',
    since: '12.2.0',
  },
  action: {
    kind: 'poke',
    agent: 'notes',
    mark: 'notes-action',
    since: '12.2.0',
  },
  // Raw eyre routes bound by %notes. Query parameters are declared in
  // send order; the path carries only holes.
  root: {
    kind: 'http',
    agent: 'notes',
    method: 'POST',
    path: '/notes/~/v1',
    since: '12.2.0',
  },
  request: {
    kind: 'http',
    agent: 'notes',
    method: 'GET',
    path: '/notes/~/v1/request/{requestId}',
    since: '12.2.0',
  },
  notebooksGet: {
    kind: 'http',
    agent: 'notes',
    method: 'GET',
    path: '/notes/~/v1/notebooks',
    since: '12.2.0',
  },
  notebooksPost: {
    kind: 'http',
    agent: 'notes',
    method: 'POST',
    path: '/notes/~/v1/notebooks',
    since: '12.2.0',
  },
  notebookGet: {
    kind: 'http',
    agent: 'notes',
    method: 'GET',
    path: '/notes/~/v1/notebooks/{host}/{name}',
    since: '12.2.0',
  },
  notesGet: {
    kind: 'http',
    agent: 'notes',
    method: 'GET',
    path: '/notes/~/v1/notebooks/{host}/{name}/notes',
    since: '12.2.0',
  },
  notesPost: {
    kind: 'http',
    agent: 'notes',
    method: 'POST',
    path: '/notes/~/v1/notebooks/{host}/{name}/notes',
    since: '12.2.0',
  },
  noteGet: {
    kind: 'http',
    agent: 'notes',
    method: 'GET',
    path: '/notes/~/v1/notebooks/{host}/{name}/notes/{id}',
    since: '12.2.0',
  },
  notePut: {
    kind: 'http',
    agent: 'notes',
    method: 'PUT',
    path: '/notes/~/v1/notebooks/{host}/{name}/notes/{id}',
    since: '12.2.0',
  },
  noteDelete: {
    kind: 'http',
    agent: 'notes',
    method: 'DELETE',
    path: '/notes/~/v1/notebooks/{host}/{name}/notes/{id}',
    since: '12.2.0',
  },
  noteHistory: {
    kind: 'http',
    agent: 'notes',
    method: 'GET',
    path: '/notes/~/v1/notebooks/{host}/{name}/notes/{id}/history',
    since: '12.2.0',
  },
  // The needle rides in the query: a dot in the last path segment would
  // be parsed as a file extension.
  search: {
    kind: 'http',
    agent: 'notes',
    method: 'GET',
    path: '/notes/~/v1/notebooks/{host}/{name}/search/bounded/text',
    query: ['needle', 'from?', 'tries?'],
    since: '12.2.0',
  },
  foldersGet: {
    kind: 'http',
    agent: 'notes',
    method: 'GET',
    path: '/notes/~/v1/notebooks/{host}/{name}/folders',
    since: '12.2.0',
  },
  foldersPost: {
    kind: 'http',
    agent: 'notes',
    method: 'POST',
    path: '/notes/~/v1/notebooks/{host}/{name}/folders',
    since: '12.2.0',
  },
  folderGet: {
    kind: 'http',
    agent: 'notes',
    method: 'GET',
    path: '/notes/~/v1/notebooks/{host}/{name}/folders/{folderId}',
    since: '12.2.0',
  },
  folderPut: {
    kind: 'http',
    agent: 'notes',
    method: 'PUT',
    path: '/notes/~/v1/notebooks/{host}/{name}/folders/{folderId}',
    since: '12.2.0',
  },
  folderDelete: {
    kind: 'http',
    agent: 'notes',
    method: 'DELETE',
    path: '/notes/~/v1/notebooks/{host}/{name}/folders/{folderId}',
    query: ['recursive'],
    since: '12.2.0',
  },
  members: {
    kind: 'http',
    agent: 'notes',
    method: 'GET',
    path: '/notes/~/v1/notebooks/{host}/{name}/members',
    since: '12.2.0',
  },
} as const satisfies Record<string, Entry>;
