export {default as Add} from './Add.svg';
export {default as Attachment} from './Attachment.svg';
export {default as Bang} from './Bang.svg';
export {default as ChannelGalleries} from './Channel_ Galleries.svg';
export {default as ChannelNote} from './Channel_ Note.svg';
export {default as ChannelNotebooks} from './Channel_ Notebooks.svg';
export {default as ChannelTalk} from './Channel_ Talk.svg';
export {default as Channel} from './Channel.svg';
export {default as Checkmark} from './Checkmark.svg';
export {default as ChevronDown} from './Chevron-Down.svg';
export {default as ChevronLeft} from './Chevron-Left.svg';
export {default as ChevronRight} from './Chevron-Right.svg';
export {default as ChevronUp} from './Chevron-Up.svg';
export {default as Clock} from './Clock.svg';
export {default as Close} from './Close.svg';
export {default as Discover} from './Discover.svg';
export {default as Dragger} from './Dragger.svg';
export {default as Face} from './Face.svg';
export {default as Filter} from './Filter.svg';
export {default as Gift} from './Gift.svg';
export {default as Home} from './Home.svg';
export {default as Label} from './Label.svg';
export {default as LeftSidebar} from './Left Sidebar.svg';
export {default as Mail} from './Mail.svg';
export {default as Messages} from './Messages.svg';
export {default as Notifications} from './Notifications.svg';
export {default as Overflow} from './Overflow.svg';
export {default as Placeholder} from './Placeholder.svg';
export {default as Profile} from './Profile.svg';
export {default as RightSidebar} from './Right Sidebar.svg';
export {default as Search} from './Search.svg';
export {default as Send} from './Send.svg';
