// This file is automatically generated by Cosmos. Add it to .gitignore and
// only edit if you know what you're doing.

import { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as fixture0 from './src/App.fixture';
import * as fixture1 from './src/fixtures/TlonButton.fixture';
import * as fixture2 from './src/fixtures/SearchBar.fixture';
import * as fixture3 from './src/fixtures/Input.fixture';
import * as fixture4 from './src/fixtures/HeaderButton.fixture';
import * as fixture5 from './src/fixtures/GroupListItem.fixture';
import * as fixture6 from './src/fixtures/GroupList.fixture';
import * as fixture7 from './src/fixtures/ChannelSwitcherSheet.fixture';
import * as fixture8 from './src/fixtures/Channel.fixture';
import * as fixture9 from './src/fixtures/Button.fixture';

import * as decorator0 from './src/fixtures/cosmos.decorator';

export const rendererConfig: RendererConfig = {
  "playgroundUrl": "http://localhost:5000",
  "rendererUrl": null
};

const fixtures = {
  'src/App.fixture.tsx': { module: fixture0 },
  'src/fixtures/TlonButton.fixture.tsx': { module: fixture1 },
  'src/fixtures/SearchBar.fixture.tsx': { module: fixture2 },
  'src/fixtures/Input.fixture.tsx': { module: fixture3 },
  'src/fixtures/HeaderButton.fixture.tsx': { module: fixture4 },
  'src/fixtures/GroupListItem.fixture.tsx': { module: fixture5 },
  'src/fixtures/GroupList.fixture.tsx': { module: fixture6 },
  'src/fixtures/ChannelSwitcherSheet.fixture.tsx': { module: fixture7 },
  'src/fixtures/Channel.fixture.tsx': { module: fixture8 },
  'src/fixtures/Button.fixture.tsx': { module: fixture9 }
};

const decorators = {
  'src/fixtures/cosmos.decorator.tsx': { module: decorator0 }
};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
