// This file is automatically generated by Cosmos. Add it to .gitignore and
// only edit if you know what you're doing.

import { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as fixture0 from './src/App.fixture';
import * as fixture1 from './src/fixtures/YStackKavDemo.fixture';
import * as fixture2 from './src/fixtures/ViewReactionsSheet.fixture';
import * as fixture3 from './src/fixtures/VideoEmbed.fixture';
import * as fixture4 from './src/fixtures/UserProfileScreen.fixture';
import * as fixture5 from './src/fixtures/Text.fixture';
import * as fixture6 from './src/fixtures/SearchBar.fixture';
import * as fixture7 from './src/fixtures/ScreenHeader.fixture';
import * as fixture8 from './src/fixtures/ReferenceSkeleton.fixture';
import * as fixture9 from './src/fixtures/ProfileSheet.fixture';
import * as fixture10 from './src/fixtures/ProfileBlock.fixture';
import * as fixture11 from './src/fixtures/PostScreen.fixture';
import * as fixture12 from './src/fixtures/PostReference.fixture';
import * as fixture13 from './src/fixtures/ParentAgnosticKeyboardAvoidingView.fixture';
import * as fixture14 from './src/fixtures/OutsideEmbed.fixture';
import * as fixture15 from './src/fixtures/MetaEditorScreen.fixture';
import * as fixture16 from './src/fixtures/MessageInput.fixture';
import * as fixture17 from './src/fixtures/MessageActions.fixture';
import * as fixture18 from './src/fixtures/InviteUsersSheet.fixture';
import * as fixture19 from './src/fixtures/InputToolbar.fixture';
import * as fixture20 from './src/fixtures/Input.fixture';
import * as fixture21 from './src/fixtures/ImageViewer.fixture';
import * as fixture22 from './src/fixtures/GroupListItem.fixture';
import * as fixture23 from './src/fixtures/GroupList.fixture';
import * as fixture24 from './src/fixtures/GalleryPost.fixture';
import * as fixture25 from './src/fixtures/Form.fixture';
import * as fixture26 from './src/fixtures/FindGroups.fixture';
import * as fixture27 from './src/fixtures/CreateGroup.fixture';
import * as fixture28 from './src/fixtures/ContactList.fixture';
import * as fixture29 from './src/fixtures/ChatMessage.fixture';
import * as fixture30 from './src/fixtures/ChannelSwitcherSheet.fixture';
import * as fixture31 from './src/fixtures/ChannelHeader.fixture';
import * as fixture32 from './src/fixtures/ChannelDivider.fixture';
import * as fixture33 from './src/fixtures/Channel.fixture';
import * as fixture34 from './src/fixtures/Button.fixture';
import * as fixture35 from './src/fixtures/BlockSectionList.fixture';
import * as fixture36 from './src/fixtures/Avatar.fixture';
import * as fixture37 from './src/fixtures/AudioEmbed.fixture';
import * as fixture38 from './src/fixtures/AttachmentPreviewList.fixture';
import * as fixture39 from './src/fixtures/AddGroupSheet.fixture';
import * as fixture40 from './src/fixtures/Activity.fixture';
import * as fixture41 from './src/fixtures/DetailView/NotebookDetailView.fixture';
import * as fixture42 from './src/fixtures/DetailView/GalleryDetailView.fixture';
import * as fixture43 from './src/fixtures/DetailView/ChatDetailView.fixture';
import * as fixture44 from './src/fixtures/ActionSheet/SendPostRetrySheet.fixture';
import * as fixture45 from './src/fixtures/ActionSheet/ProfileSheet.fixture';
import * as fixture46 from './src/fixtures/ActionSheet/GroupPreviewSheet.fixture';
import * as fixture47 from './src/fixtures/ActionSheet/GroupJoinRequestSheet.fixture';
import * as fixture48 from './src/fixtures/ActionSheet/GenericActionSheet.fixture';
import * as fixture49 from './src/fixtures/ActionSheet/EditSectionNameSheet.fixture';
import * as fixture50 from './src/fixtures/ActionSheet/DeleteSheet.fixture';
import * as fixture51 from './src/fixtures/ActionSheet/CreateChannelSheet.fixture';
import * as fixture52 from './src/fixtures/ActionSheet/ChannelSortActionsSheet.fixture';
import * as fixture53 from './src/fixtures/ActionSheet/AttachmentSheet.fixture';
import * as fixture54 from './src/fixtures/ActionSheet/AddGalleryPostSheet.fixture';

import * as decorator0 from './src/fixtures/cosmos.decorator';

export const rendererConfig: RendererConfig = {
  "playgroundUrl": "http://localhost:5001",
  "rendererUrl": null
};

const fixtures = {
  'src/App.fixture.tsx': { module: fixture0 },
  'src/fixtures/YStackKavDemo.fixture.tsx': { module: fixture1 },
  'src/fixtures/ViewReactionsSheet.fixture.tsx': { module: fixture2 },
  'src/fixtures/VideoEmbed.fixture.tsx': { module: fixture3 },
  'src/fixtures/UserProfileScreen.fixture.tsx': { module: fixture4 },
  'src/fixtures/Text.fixture.tsx': { module: fixture5 },
  'src/fixtures/SearchBar.fixture.tsx': { module: fixture6 },
  'src/fixtures/ScreenHeader.fixture.tsx': { module: fixture7 },
  'src/fixtures/ReferenceSkeleton.fixture.tsx': { module: fixture8 },
  'src/fixtures/ProfileSheet.fixture.tsx': { module: fixture9 },
  'src/fixtures/ProfileBlock.fixture.tsx': { module: fixture10 },
  'src/fixtures/PostScreen.fixture.tsx': { module: fixture11 },
  'src/fixtures/PostReference.fixture.tsx': { module: fixture12 },
  'src/fixtures/ParentAgnosticKeyboardAvoidingView.fixture.tsx': { module: fixture13 },
  'src/fixtures/OutsideEmbed.fixture.tsx': { module: fixture14 },
  'src/fixtures/MetaEditorScreen.fixture.tsx': { module: fixture15 },
  'src/fixtures/MessageInput.fixture.tsx': { module: fixture16 },
  'src/fixtures/MessageActions.fixture.tsx': { module: fixture17 },
  'src/fixtures/InviteUsersSheet.fixture.tsx': { module: fixture18 },
  'src/fixtures/InputToolbar.fixture.tsx': { module: fixture19 },
  'src/fixtures/Input.fixture.tsx': { module: fixture20 },
  'src/fixtures/ImageViewer.fixture.tsx': { module: fixture21 },
  'src/fixtures/GroupListItem.fixture.tsx': { module: fixture22 },
  'src/fixtures/GroupList.fixture.tsx': { module: fixture23 },
  'src/fixtures/GalleryPost.fixture.tsx': { module: fixture24 },
  'src/fixtures/Form.fixture.tsx': { module: fixture25 },
  'src/fixtures/FindGroups.fixture.tsx': { module: fixture26 },
  'src/fixtures/CreateGroup.fixture.tsx': { module: fixture27 },
  'src/fixtures/ContactList.fixture.tsx': { module: fixture28 },
  'src/fixtures/ChatMessage.fixture.tsx': { module: fixture29 },
  'src/fixtures/ChannelSwitcherSheet.fixture.tsx': { module: fixture30 },
  'src/fixtures/ChannelHeader.fixture.tsx': { module: fixture31 },
  'src/fixtures/ChannelDivider.fixture.tsx': { module: fixture32 },
  'src/fixtures/Channel.fixture.tsx': { module: fixture33 },
  'src/fixtures/Button.fixture.tsx': { module: fixture34 },
  'src/fixtures/BlockSectionList.fixture.tsx': { module: fixture35 },
  'src/fixtures/Avatar.fixture.tsx': { module: fixture36 },
  'src/fixtures/AudioEmbed.fixture.tsx': { module: fixture37 },
  'src/fixtures/AttachmentPreviewList.fixture.tsx': { module: fixture38 },
  'src/fixtures/AddGroupSheet.fixture.tsx': { module: fixture39 },
  'src/fixtures/Activity.fixture.tsx': { module: fixture40 },
  'src/fixtures/DetailView/NotebookDetailView.fixture.tsx': { module: fixture41 },
  'src/fixtures/DetailView/GalleryDetailView.fixture.tsx': { module: fixture42 },
  'src/fixtures/DetailView/ChatDetailView.fixture.tsx': { module: fixture43 },
  'src/fixtures/ActionSheet/SendPostRetrySheet.fixture.tsx': { module: fixture44 },
  'src/fixtures/ActionSheet/ProfileSheet.fixture.tsx': { module: fixture45 },
  'src/fixtures/ActionSheet/GroupPreviewSheet.fixture.tsx': { module: fixture46 },
  'src/fixtures/ActionSheet/GroupJoinRequestSheet.fixture.tsx': { module: fixture47 },
  'src/fixtures/ActionSheet/GenericActionSheet.fixture.tsx': { module: fixture48 },
  'src/fixtures/ActionSheet/EditSectionNameSheet.fixture.tsx': { module: fixture49 },
  'src/fixtures/ActionSheet/DeleteSheet.fixture.tsx': { module: fixture50 },
  'src/fixtures/ActionSheet/CreateChannelSheet.fixture.tsx': { module: fixture51 },
  'src/fixtures/ActionSheet/ChannelSortActionsSheet.fixture.tsx': { module: fixture52 },
  'src/fixtures/ActionSheet/AttachmentSheet.fixture.tsx': { module: fixture53 },
  'src/fixtures/ActionSheet/AddGalleryPostSheet.fixture.tsx': { module: fixture54 }
};

const decorators = {
  'src/fixtures/cosmos.decorator.tsx': { module: decorator0 }
};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
