// This file is automatically generated by Cosmos. Add it to .gitignore and
// only edit if you know what you're doing.

import { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import './apps/tlon-web-new/cosmos/setup';

import * as fixture0 from './src/fixtures/Button.fixture';

export const rendererConfig: RendererConfig = {
  "playgroundUrl": "http://localhost:5000",
  "rendererUrl": "http://localhost:5050/apps/groups/"
};

const fixtures = {
  'src/fixtures/Button.fixture.tsx': { module: fixture0 }
};

const decorators = {};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
