// DO NOT EDIT THIS FILE MANUALLY
// Regenerate using the Text fixture and use the "copy margin settings" to
// grab values to paste in here.
// If you need to override any of these values, do so in Text.tsx.

export const trimIos = {
  '$mono/s': {
    marginTop: -5.810546874999998,
    marginBottom: -5.734374999999998,
  },
  '$mono/m': {
    marginTop: -7.1123046875,
    marginBottom: -7.0234375,
  },
  '$emoji/m': {
    marginTop: -4.13818359375,
    marginBottom: -5.0654296875,
  },
  '$emoji/l': {
    marginTop: -5.951171875,
    marginBottom: -8.68359375,
  },
  '$label/s': {
    marginTop: -3.810546875,
    marginBottom: -3.734375,
  },
  '$label/m': {
    marginTop: -5.112304687499998,
    marginBottom: -5.023437499999998,
  },
  '$label/l': {
    marginTop: -6.4140625,
    marginBottom: -6.3125,
  },
  '$label/xl': {
    marginTop: -6.06494140625,
    marginBottom: -5.95703125,
  },
  '$label/2xl': {
    marginTop: -6.06494140625,
    marginBottom: -5.95703125,
  },
  '$label/3xl': {
    marginTop: -3.083984375,
    marginBottom: -4.82421875,
  },
  $body: {
    marginTop: -6.4140625,
    marginBottom: -6.3125,
  },
  '$title/l': {
    marginTop: -1.8427734375,
    marginBottom: -8.201171875,
  },
};

export const trimAndroid = {
  '$mono/s': {
    marginTop: -6.0952372550964355,
    marginBottom: -5.333333492279053,
  },
  '$mono/m': {
    marginTop: -7.390476226806641,
    marginBottom: -6.476190567016602,
  },
  '$emoji/m': {
    marginTop: -3.3333332538604736,
    marginBottom: -5.333333730697632,
  },
  '$emoji/l': {
    marginTop: 0,
    marginBottom: -2,
  },
  '$label/s': {
    marginTop: -0.3809525966644287,
    marginBottom: -3.047619104385376,
  },
  '$label/m': {
    marginTop: -5.485713481903076,
    marginBottom: -4.5714287757873535,
  },
  '$label/l': {
    marginTop: -6.784761428833008,
    marginBottom: -5.714285850524902,
  },
  '$label/xl': {
    marginTop: -6.342857599258423,
    marginBottom: -5.333333730697632,
  },
  '$label/2xl': {
    marginTop: -6.342857599258423,
    marginBottom: -5.333333730697632,
  },
  '$label/3xl': {
    marginTop: -2.6285715103149414,
    marginBottom: -4.952381134033203,
  },
  $body: {
    marginTop: -6.784761428833008,
    marginBottom: -5.714285850524902,
  },
  '$title/l': {
    marginTop: -1.2609500885009766,
    marginBottom: -8.380952835083008,
  },
};
