// Shared core for generate-tokens.mjs and check-token-drift.mjs: evaluate
// @tloncorp/ui's Tamagui config (the designers' single source of truth)
// and emit the shell's CSS custom properties.
//
// Mapping policy (D-logged): only what the primitive kit needs — the
// light/dark theme color roles the primitives use, the small/medium end of
// the spacing and radius scales, and the system font's core type scale.
// Exotic themes (dracula, gruvbox) and app-specific roles (unread dots,
// system notices, overlays) are deliberately not mapped; additions are
// additive within a shell major.
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";

const packageRoot = join(fileURLToPath(import.meta.url), "..", "..");
const repoRoot = join(packageRoot, "..", "..");
const shim = (name) => join(packageRoot, "scripts", "shims", name);

async function loadTamaguiConfig() {
  const server = await createServer({
    configFile: false,
    root: repoRoot,
    logLevel: "error",
    server: { middlewareMode: true, hmr: false },
    optimizeDeps: { noDiscovery: true },
    // aliases don't apply to SSR-externalized deps; keep everything in
    // vite's pipeline so the shims actually shadow the real packages
    ssr: { noExternal: true },
    resolve: {
      alias: {
        tamagui: shim("tamagui.mjs"),
        "react-native": shim("react-native.mjs"),
        "@tamagui/animations-moti": shim("tamagui-extras.mjs"),
        "@tamagui/react-native-media-driver": shim("tamagui-extras.mjs"),
      },
    },
  });
  try {
    return await server.ssrLoadModule("/packages/ui/tamagui.config.ts");
  } finally {
    await server.close();
  }
}

/** theme role → shell variable (colors are theme-scoped) */
const COLOR_MAP = {
  background: "color-bg",
  secondaryBackground: "color-bg-secondary",
  primaryText: "color-text",
  secondaryText: "color-text-secondary",
  tertiaryText: "color-text-tertiary",
  border: "color-border",
  secondaryBorder: "color-border-secondary",
  activeBorder: "color-border-active",
  positiveActionText: "color-positive-text",
  positiveBackground: "color-positive-bg",
  positiveBorder: "color-positive-border",
  negativeActionText: "color-negative-text",
  negativeBackground: "color-negative-bg",
  negativeBorder: "color-negative-border",
  shadow: "color-shadow",
};

const THEMES = ["light", "dark"];
const SPACE_KEYS = ["2xs", "xs", "s", "m", "l", "xl", "2xl", "3xl", "4xl"];
const RADIUS_KEYS = ["xs", "s", "m", "l", "xl", "2xl"];
const TEXT_SIZE_KEYS = ["xs", "s", "m", "l", "xl"];
const LINE_HEIGHT_KEYS = ["xs", "s", "m", "l"];

function cssName(key) {
  return key.replace(".", "_");
}

export async function generateTokensCss() {
  const { themes, tokens, systemFont } = await loadTamaguiConfig();

  const lines = [];
  lines.push("/*");
  lines.push(" * GENERATED by scripts/generate-tokens.mjs from");
  lines.push(" * @tloncorp/ui's tamagui.config.ts — do not edit by hand.");
  lines.push(" * Regenerate with `pnpm generate:tokens`;");
  lines.push(" * `pnpm check:tokens` fails CI when this file is stale.");
  lines.push(" */");
  lines.push("");

  // theme-independent tokens
  lines.push(":root {");
  lines.push(
    `  --font-family: ${systemFont.family};`,
    `  --font-mono: ui-monospace, Menlo, monospace;`,
  );
  for (const key of TEXT_SIZE_KEYS) {
    lines.push(`  --text-${cssName(key)}: ${systemFont.size[key]}px;`);
  }
  for (const key of LINE_HEIGHT_KEYS) {
    lines.push(`  --line-${cssName(key)}: ${systemFont.lineHeight[key]}px;`);
  }
  lines.push("  --weight-regular: 400;");
  lines.push("  --weight-medium: 500;");
  for (const key of SPACE_KEYS) {
    lines.push(`  --space-${cssName(key)}: ${tokens.space[key].val}px;`);
  }
  for (const key of RADIUS_KEYS) {
    lines.push(`  --radius-${cssName(key)}: ${tokens.radius[key].val}px;`);
  }
  lines.push("}");
  lines.push("");

  // theme-scoped colors; light doubles as the default so an unthemed root
  // still renders
  for (const theme of THEMES) {
    const selector =
      theme === "light" ? `:root, [data-theme='light']` : `[data-theme='dark']`;
    lines.push(`${selector} {`);
    for (const [role, variable] of Object.entries(COLOR_MAP)) {
      const value = themes[theme][role];
      if (value === undefined) {
        throw new Error(`theme '${theme}' is missing role '${role}'`);
      }
      lines.push(`  --${variable}: ${value};`);
    }
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

export const TOKENS_CSS_PATH = join(packageRoot, "src", "tokens", "tokens.css");
