name: Build and Glob
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
        default: develop
        description: Enter the tag to deploy
env:
  tag: ${{ github.event.inputs.tag || 'develop' }}
concurrency:
  group: ${{ format('{0}-{1}', github.ref, 'build-and-glob') }}
  cancel-in-progress: true
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: "Build Frontend"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.tag }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
      - name: Build packages
        run: pnpm build:all
      - working-directory: ./apps/tlon-web
        run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: "ui-dist"
          path: apps/tlon-web/dist
    env:
      VITE_BRANCH_DOMAIN_PROD: ${{ secrets.VITE_BRANCH_DOMAIN_PROD}}
      VITE_BRANCH_DOMAIN_TEST: ${{ secrets.VITE_BRANCH_DOMAIN_TEST}}
      VITE_BRANCH_KEY_PROD: ${{ secrets.VITE_BRANCH_KEY_PROD}}
      VITE_BRANCH_KEY_TEST: ${{ secrets.VITE_BRANCH_KEY_TEST}}
      VITE_INVITE_SERVICE_ENDPOINT: ${{ secrets.VITE_INVITE_SERVICE_ENDPOINT}}
      VITE_POST_HOG_API_KEY: ${{ secrets.VITE_POST_HOG_API_KEY}}
  glob:
    runs-on: ubuntu-latest
    name: "Make a glob"
    needs: build-frontend
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.tag }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/download-artifact@v4
        with:
          name: "ui-dist"
          path: apps/tlon-web/dist
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_KEY }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      - name: "glob"
        uses: ./.github/actions/glob
        with:
          folder: "apps/tlon-web/dist/*"
          docket: "desk/desk.docket-0"
      - name: Commit and Push Glob
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add desk/desk.docket-0
          git commit -n -m "update glob: ${{ steps.glob.outputs.hash }} [skip actions]" || echo "No changes to commit"
          INPUT=${{ env.tag }}
          BRANCH=${INPUT:-"develop"}
          git pull origin $BRANCH --rebase --autostash
          git push
