name: Version Bump
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
        default: develop
        description: Enter the target branch
      version:
        type: string
        required: true
        description: Enter the version
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Bumps versions and pushes to develop"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Bump
        run: |
          sed -i "s/version+\[.*]/version+[${{ github.event.inputs.version }}]/" desk/desk.docket-0
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "-A"
          message:
            "version bump: ${{ github.event.inputs.version }} [skip actions]"
