name: Deploy Groups (internal)
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: Enter the tag to deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Release to ~marnec-dozzod-marnus (internal)"
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - id: deploy
        name: Deploy
        run:
          ./.github/helpers/deploy.sh tloncorp/tlon-apps groups marnec-dozzod-marnus us-central1-a mainnet-tlon-other-2d ${{ github.event.inputs.tag }}
        env:
          SSH_SEC_KEY: ${{ secrets.GCP_SSH_SEC_KEY }}
          SSH_PUB_KEY: ${{ secrets.GCP_SSH_PUB_KEY }}
          URBIT_REPO_TAG: ${{ vars.URBIT_REPO_TAG }}
  deploy-new:
    runs-on: ubuntu-latest
    name: "Release new frontend to ~marnec-dozzod-marnus (internal)"
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - id: deploy
        name: Deploy
        run:
          ./.github/helpers/deploy.sh tloncorp/tlon-apps tm-alpha marnec-dozzod-marnus us-central1-a mainnet-tlon-other-2d ${{ github.event.inputs.tag }}
        env:
          SSH_SEC_KEY: ${{ secrets.GCP_SSH_SEC_KEY }}
          SSH_PUB_KEY: ${{ secrets.GCP_SSH_PUB_KEY }}
          URBIT_REPO_TAG: ${{ vars.URBIT_REPO_TAG }}
