name: Glob and Deploy Groups (Kernel Integration)
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
        default: develop
        description: Enter the tag to deploy
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: "Build Frontend"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
      - working-directory: ./apps/tlon-web
        run: pnpm build
      - uses: actions/upload-artifact@v3
        with:
          name: "ui-dist"
          path: apps/tlon-web/dist
  glob:
    runs-on: ubuntu-latest
    name: "Make a glob"
    needs: build-frontend
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - uses: actions/download-artifact@v3
        with:
          name: "ui-dist"
          path: apps/tlon-web/dist
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_KEY }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      - name: "glob"
        uses: ./.github/actions/glob
        with:
          folder: "apps/tlon-web/dist/*"
          docket: "desk/desk.docket-0"
      - name: Commit and Push Glob
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add desk/desk.docket-0
          git commit -n -m "update glob: ${{ steps.glob.outputs.hash }} [skip actions]" || echo "No changes to commit"
          INPUT=${{ github.event.inputs.tag }}
          BRANCH=${INPUT:-"develop"}
          git pull origin $BRANCH --rebase --autostash
          git push
  deploy:
    runs-on: ubuntu-latest
    needs: glob
    name: "Deploy Groups to ~bosdev-dozzod-marnus (kernel integration)"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_KEY }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      - id: deploy
        name: Deploy
        run: ./.github/helpers/deploy.sh tloncorp/tlon-apps groups bosdev-dozzod-marnus us-central1-b mainnet-tlon-other-2d ${{ github.event.inputs.tag }}
        env:
          SSH_SEC_KEY: ${{ secrets.GCP_SSH_SEC_KEY }}
          SSH_PUB_KEY: ${{ secrets.GCP_SSH_PUB_KEY }}
          URBIT_REPO_TAG: ${{ vars.URBIT_REPO_TAG_KERNEL }}
